name: 'coverage'
on:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  pull-requests: write
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: packages/react-form-validation
