name: 'coverage'
on:
  pull_request_target:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: packages/react-form-validation
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
